data:
    dataset: 'Cityscapes'  # 'coco' 'hpatches'
    export_folder: 'train' # train, val
    preprocessing:
        resize: [240, 320] 
        # resize: [480, 640] 
    gaussian_label:
        enable: false # false
        sigma: 1.
    augmentation:
        photometric:
            enable: false
    homography_adaptation:
        enable: false
        num: 50 # 100
        aggregation: 'sum'
        filter_counts: 0
        homographies:
            params:
                translation: true
                rotation: true
                scaling: true
                perspective: true
                scaling_amplitude: 0.2
                perspective_amplitude_x: 0.2
                perspective_amplitude_y: 0.2
                allow_artifacts: true
                patch_ratio: 0.85
    warped_pair:
        enable: true
        params:
            translation: true
            rotation: true
            scaling: true
            perspective: true
            scaling_amplitude: 0.01  # reduced for gentler warp
            perspective_amplitude_x: 0.05  # reduced for gentler warp
            perspective_amplitude_y: 0.05  # reduced for gentler warp
            patch_ratio: 0.95  # wider valid area
            max_angle: 0.3  # ~17 degrees
            allow_artifacts: true
        valid_border_margin: 3

training:
    workers_train: 16
    workers_val: 16
    workers_test: 16

model:
    # name: 'SuperPointNet' # 'SuperPointNet_gauss2'
    name: 'SuperPointNet_gauss2' # 'SuperPointNet_gauss2'
    params: {
    }    
    batch_size: 8
    eval_batch_size: 8
    detection_threshold: 0.005 # 0.015
    nms: 2
    top_k: 4096
    subpixel:
        enable: true
    nn_thresh: 0.7
    # pretrained: 'logs/magicpoint_synth20/checkpoints/superPointNet_200000_checkpoint.pth.tar' # 'SuperPointNet'
    pretrained: 'logs/magicpoint_synth/checkpoints/superPointNet_20000_checkpoint.pth.tar' # Newer version with 100k iterations

pretrained: 'logs/magicpoint_synth/checkpoints/superPointNet_20000_checkpoint.pth.tar' # Newer version with 100k iterations


