# Configuration for exporting SuperPoint predictions on the Cityscapes dataset
# This loads the fine-tuned model and writes predictions for the "val" split

data:
    name: 'Cityscapes'
    dataset: 'Cityscapes'            # dataset name
    alteration: 'all'                # 'all' 'i' 'v'
    export_folder: 'val'             # choose split
    root: 'datasets/Cityscapes'      # path to Cityscapes images
    segmentation_labels: 'datasets/Cityscapes/gtFine'  # segmentation masks
    preprocessing:
        resize: [512, 1024]
    gaussian_label:
        enable: false
        sigma: 1.
    augmentation:
        photometric:
            enable: false
    homography_adaptation:
        enable: true
        num: 100
        aggregation: 'sum'
        filter_counts: 0
        homographies:
            params:
                translation: true
                rotation: true
                scaling: true
                perspective: true
                scaling_amplitude: 0.2
                perspective_amplitude_x: 0.2
                perspective_amplitude_y: 0.2
                allow_artifacts: true
                patch_ratio: 0.85

training:
    workers_test: 2

# model used for exporting
front_end_model: 'Val_model_heatmap'  # 'Train_model_frontend'

model:
    name: 'SuperPointNet_gauss2'
    params: {}
    batch_size: 1
    eval_batch_size: 1
    detection_threshold: 0.015
    nms: 4
    top_k: 600
    subpixel:
        enable: true

# Path to the fine-tuned checkpoint to load before export
pretrained: 'logs/superpoint_cityscapes/checkpoints/superPointNet_best.pth.tar'

# evaluate only once
eval_iter: 100

