# Configuration for exporting SuperPoint predictions on the Cityscapes dataset
# This loads the fine-tuned model and writes predictions for the "val" split

data:
    name: 'Cityscapes'
    dataset: 'Cityscapes'            # dataset name
    alteration: 'all'                # 'all' 'i' 'v'
    export_folder: 'val'             # choose split
    root: 'datasets/Cityscapes'      # path to Cityscapes images
    segmentation_labels: 'datasets/Cityscapes/gtFine'  # segmentation masks
    preprocessing:
        resize: [240, 320] #[512, 1024]
    reduce_to_4_categories: true
    # generate a warped image pair similar to the training setup
    warped_pair:
        enable: true
        params:
            translation: true
            rotation: true
            scaling: true
            perspective: true
            scaling_amplitude: 0.01
            perspective_amplitude_x: 0.005
            perspective_amplitude_y: 0.005
            patch_ratio: 0.9
            allow_artifacts: false
        valid_border_margin: 3
training:
    workers_train: 8
    workers_val: 8
    workers_test: 8

# model used for exporting
front_end_model: 'Val_model_heatmap'  # 'Train_model_frontend'

model:
    name: 'SuperPointNet_gauss2'
    params: {}
    lambda_segmentation: 1.0
    num_segmentation_classes: 4

    # learning_rate: 0.0001 # 0.0001
    detection_threshold: 0.001 # 0.015

    batch_size: 8
    eval_batch_size: 8
    # output parameters
    learning_rate: 0.001
    detection_threshold: 0.001 # 0.001
    nms: 3
    top_k: 1000
    nn_thresh: 0.7 # 0.7
    homography_adaptation:
        num: 50
    subpixel:
        enable: true
        patch_size: 5
    rand_noise:
        enable: false
        sigma: 0.2
    # Path to the fine-tuned checkpoint to load before export
    pretrained: 'logs/superpoint_cityscapes/checkpoints/superPointNet_100_checkpoint.pth.tar'

# evaluate only once
eval_iter: 50

