# Configuration for training SuperPoint on the Cityscapes dataset
# Segmentation labels can be reduced to 4 coarse categories

data:
    dataset: 'Cityscapes'
    root: 'datasets/Cityscapes'  # path to Cityscapes images
    labels: logs/magicpoint_synth_homoAdapt_cityscape/predictions
    segmentation_labels: 'datasets/Cityscapes/gtFine'  # segmentation masks
    cache_in_memory: false
    load_segmentation: true
    reduce_to_4_categories: true
    num_segmentation_classes: 4
    gaussian_label:
        enable: true
        params:
            GaussianBlur: {sigma: 0.2}
    preprocessing:
        resize: [240, 320] #[512, 1024]  # images are downsampled for training
    augmentation:
        photometric:
            enable: true
            primitives: [
                'random_brightness', 'random_contrast', 'additive_speckle_noise',
                'additive_gaussian_noise', 'additive_shade', 'motion_blur']
            params:
                random_brightness: {max_abs_change: 50}
                random_contrast: {strength_range: [0.5, 1.5]}
                additive_gaussian_noise: {stddev_range: [0, 10]}
                additive_speckle_noise: {prob_range: [0, 0.0035]}
                additive_shade:
                    transparency_range: [-0.5, 0.5]
                    kernel_size_range: [100, 150]
                motion_blur: {max_kernel_size: 3}
        homographic:
            enable: true
            num_homographies: 10       # samples per image for aggregation
            max_angle: 0.005             # in radians (~10°)
            translate: 0.005              # relative to image size
            scale: [0.03, 0.05]
            perspective: 0.005
            allow_artifacts: false
    warped_pair:
        enable: true
        params:
            translation: true
            rotation: true
            scaling: true
            perspective: true
            scaling_amplitude: 0.005  # reduced for gentler warp
            perspective_amplitude_x: 0.005  # reduced for gentler warp
            perspective_amplitude_y: 0.005  # reduced for gentler warp
            patch_ratio: 0.9  # wider valid area
            max_angle: 0.1  # ~17 degrees
            allow_artifacts: false
        valid_border_margin: 3

front_end_model: 'Train_model_heatmap'  # use heatmap detector
training:
    workers_train: 8
    workers_val: 8
    workers_test: 8

model:
    name: 'SuperPointNet_gauss2'
    params: {}
    detector_loss:
        loss_type: 'softmax'

    batch_size: 8
    eval_batch_size: 8
    learning_rate: 0.0001  # reasonable learning rate
    detection_threshold: 0.005
    lambda_loss: 1
    lambda_segmentation: 1.0
    num_segmentation_classes: 4
    compute_miou: true  # log mIoU for each batch
    freeze_det_desc: true  # only finetune segmentation head
    nms: 3
    dense_loss:
        enable: false
        params:
            descriptor_dist: 4
            lambda_d: 800
    sparse_loss:
        enable: true
        params:
            num_matching_attempts: 100
            num_masked_non_matches_per_match: 10
            lamda_d: 1
            dist: 'cos'
            method: '2d'
    other_settings: 'train 2d, gauss 0.2'

retrain: True
reset_iter: True
train_iter: 100 #170000
validation_interval: 25 #2000
tensorboard_interval: 25
save_interval: 25 #2000
validation_size: 5
truncate: 100

pretrained: 'logs/superpoint_coco/checkpoints/superPointNet_200_checkpoint.pth.tar'
    # pretrained: 'logs/superpoint_coco_heat2_0/checkpoints/superPointNet_90000_checkpoint.pth.tar'

