# This workflow will triage pull requests and apply a label based on the
# paths that are modified in the pull request.
#
# To use this workflow, you will need to set up a .github/labeler.yml
# file with configuration.  For more information, see:
# https://github.com/actions/labeler

name: Auto Remove labels
on:
  pull_request:
    types: [labeled]

permissions:
  issues: write
  pull-requests: write

jobs:
  zap-label:
    runs-on: ubuntu-latest
    steps:
      - name: Remove the label
        uses: actions-ecosystem/action-remove-labels@v
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: ${{ github.event.label.name }}
